### ISSUE TITLE
Zookeeper Release File Not Found.

### ISSUE THREAD

**Issue by medined** [chadgeary/nifi-amazon-linux#1]
When I look at the Apache Zookeeper release page, the top recommendation does not have the same URL pattern at that in zookeepers.yml.

This is the URL from the yaml file.

```
http://{{ mirror_host }}/pub/apache/zookeeper/current/apache-zookeeper-{{ zk_version }}-bin.tar.gz
```

This is the recommended URL.

```
http://mirror.cc.columbia.edu/pub/software/apache/zookeeper/zookeeper-3.6.2/apache-zookeeper-3.6.2-bin.tar.gz
```

Perhaps using a zk_download_url in a variable instead of using a mirror_host and zk_version would be less brittle?

Although, I really don't know why Apache doesn't have some kind of load balancer amount the host mirrors.

**Comment by chadgeary** [comment]
Good catch - I’ll put something in the README about it.

I’m thinking about the weight of too many variables (which isn’t REALLY a bad thing) and code complexity. Filling in the URL for three different packages (zookeeper, nifi, and toolkit) and having the administrator discern which are valid feels like a headache.

cogentco is usually very fast, btw.

**Comment by chadgeary** [comment]
[Fixed](https://github.com/chadgeary/nifi-amazon-linux/commit/48b4e99c75d0e9c57fa4caae8a10d3849076196c) and supports older versions as most mirrors do not host more than 1 to 2 versions.
